query factionUnitsQuery($tww_version: String!, $faction: String! ) {
  tww(tww_version: $tww_version) {
    tww_version
    faction(id: $faction) {
      key
      screen_name
      subculture {
        name
      }
      flags_url
      units(groupHeroesAndLords: true) {
        unit
        caste
        num_men
        multiplayer_cost
        unit_sets {
          special_category
        }
        custom_battle_permissions {
          general_portrait
          campaign_exclusive
          set_piece_character {
            ancillaries {
              ancillary_effects {
                effect {
                  abilities {
                    ...effect_bonus

                  }
                }
              }
            }
          }
        }
        land_unit {
          onscreen_name
          variant {
            unit_card_url
          }
          battle_entity {
            size
          }
          abilities {
            icon_name
            key
            name
            tooltip
          }
          attributes {
            key
            bullet_text
            imbued_effect_text
          }
          special_ability_groups {
            abilities {
              icon_name
              key
              name
              tooltip
            }
          }
        }
        ui_unit_group {
          icon
          key
          name
          tooltip
          parent_group {
              key
              onscreen_name
              icon
              order

          }
        }
      }
    }
  }
}