query factionUnitsQuery($tww_version: String!, $faction: String! ) {
  tww(tww_version: $tww_version) {
    tww_version
    faction(id: $faction) {
      units(groupHeroesAndLords: true) {
        unit
        caste
        num_men
        multiplayer_cost
        unit_sets {
          special_category
          __typename
        }
        custom_battle_permissions {
          general_portrait
          __typename
        }
        land_unit {
          onscreen_name
          variant {
            unit_card_url
            __typename
          }
          battle_entity {
            size
          }
          __typename
        }
        ui_unit_group {
          icon
          key
          name
          tooltip
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}