query UnitQuery($tww_version: String!, $key: String!) {
    tww(tww_version: $tww_version) {
        tww_version
        game_version {
            name
        }
        unit(id: $key) {
            unit
            tier
            unit_sets {
                special_category
            }
            num_men
            caste
            multiplayer_cost
            recruitment_cost
            weight
            upkeep_cost
            create_time
            mount_name
            barrier_health
            is_high_threat
            can_siege
            bullet_points {
                key
                state
                sort_order
                onscreen_name
                tooltip
            }
            battle_mounts {
                base_unit
                mounted_unit
                icon_name
                mount_name
                localised_description
            }
            custom_battle_permissions {
                general_portrait
                campaign_exclusive
                set_piece_character {
                    ancillaries {
                        ancillary_effects {
                            effect {
                                abilities {
                                    ...effect_bonus

                                }
                            }
                        }
                    }
                }
            }
            ui_unit_group {
                key
                icon
                name
                parent_group {
                    key
                    onscreen_name
                    order
                }
                tooltip
            }
            factions(include_non_mp: false) {
                key
                screen_name
                flags_url
                name_group
            }
            land_unit {
                key
                short_description_text
                mount {
                    key
                }
                variant {
                    variant
                    unit
                    name
                    unit_card_url
                }
                ground_stat_effect_group {
                    group_name
                    onscreen_name
                    stat_effects {
                        ground_type
                        affected_group
                        affected_stat
                        multiplier
                    }
                }
                num_engines
                num_mounts
                onscreen_name
                accuracy
                category
                charge_bonus
                melee_attack
                melee_defence
                morale
                bonus_hit_points
                attribute_group
                reload
                secondary_ammo
                primary_ammo
                damage_mod_flame
                damage_mod_magic
                damage_mod_physical
                damage_mod_missile
                damage_mod_all
                can_skirmish
                abilities {
                    icon_name
                    key
                    name
                    tooltip
                }
                attributes {
                    key
                    bullet_text
                    imbued_effect_text
                }
                special_ability_groups {
                    abilities {
                        icon_name
                        key
                        name
                        tooltip
                    }
                }
                armour {
                    key
                    armour_value
                }
                unit_class {
                    key
                    onscreen
                }
                primary_melee_weapon {
                    key
                    bonus_v_cavalry
                    bonus_v_large
                    bonus_v_infantry
                    damage
                    ap_damage
                    weapon_length
                    melee_weapon_type
                    splash_attack_target_size
                    splash_attack_max_attacks
                    splash_attack_power_multiplier
                    ignition_amount
                    is_magical
                    contact_phase {
                        ...contact_phase
                    }
                    collision_attack_max_targets
                    collision_attack_max_targets_cooldown
                    melee_attack_interval
                }
                primary_missile_weapon {
                    use_secondary_ammo_pool
                    default_projectile {
                        ...projectile
                    }
                }
                shield {
                    key
                    parry_chance
                    material
                }
                battle_entity {
                    ...battle_entity
                }
                mount {
                    key
                    variant
                    battle_entity {
                        ...battle_entity
                    }
                }
                engine {
                    key
                    engine_type
                    missile_weapon {
                        use_secondary_ammo_pool
                        default_projectile {
                            ...projectile

                        }
                    }
                    battle_entity {
                        ...battle_entity

                    }
                }
                articulated_vehicle_entity {
                    hit_points

                }
            }
        }
    }
}
fragment contact_phase on phase {
    id
    onscreen_name
    duration
    effect_type
    requested_stance
    unbreakable
    cant_move
    freeze_fatigue
    fatigue_change_ratio
    ability_recharge_change
    hp_change_frequency
    heal_amount
    damage_chance
    damage_amount
    max_damaged_entities
    resurrect
    mana_regen_mod
    mana_max_depletion_mod
    imbue_magical
    imbue_ignition
    phase_display
    imbue_contact {
        id
        onscreen_name
        duration
        effect_type
        requested_stance
        unbreakable
        cant_move
        freeze_fatigue
        fatigue_change_ratio
        ability_recharge_change
        hp_change_frequency
        heal_amount
        damage_chance
        damage_amount
        max_damaged_entities
        resurrect
        mana_regen_mod
        mana_max_depletion_mod
        imbue_magical
        imbue_ignition
        phase_display
        stat_effects {
            phase
            stat
            value
            how
        }
        attribute_effects {
            phase
            attribute
            attribute_type

        }
    }
    stat_effects {
        phase
        stat
        value
        how
    }
    attribute_effects {
        phase
        attribute
        attribute_type
    }
}
fragment projectile on projectile {
    key
    category
    shot_type
    explosion {
        ...explosion
    }
    projectile_number
    effective_range
    minimum_range
    marksmanship_bonus
    damage
    ap_damage
    collision_radius
    base_reload_time
    bonus_v_cavalry
    bonus_v_infantry
    bonus_v_large
    calibration_distance
    calibration_area
    max_elevation
    overhead_stat_effect {
        ...contact_phase
    }
    contact_stat_effect {
        ...contact_phase
    }
    projectile_penetration {
        key
        entity_size_cap
        max_penetration
        description
    }
    burst_size
    burst_shot_delay
    ignition_amount
    is_magical
    shots_per_volley
    can_damage_buildings
}
fragment explosion on explosion {
    key
    detonation_damage
    detonation_damage_ap
    is_magical
    ignition_amount
    detonation_radius
    detonation_duration
    detonation_speed
    shrapnel_amount
    distance_from_target
    detonation_force
    shrapnel_type
    contact_phase_effect {
        ...contact_phase

    }
}
fragment battle_entity on battle_entity {
    key
    type
    run_speed
    mass
    hit_points
    fly_speed
    charge_speed
    flying_charge_speed
    acceleration
    deceleration
    size
    radius
    height
    hit_reactions_ignore_chance
    knock_interrupts_ignore_chance
    charge_distance_commence_run
    charge_distance_adopt_charge_pose
    charge_distance_pick_target
    combat_reaction_radius
}
fragment effect_bonus on effect_bonus {
    bonus_value_id
    value {
        ... on agent_action {
            localised_action_name
        }
        ... on phase {
            ...contact_phase
        }
        ... on ability {
            key
            supercedes_ability
            requires_effect_enabling
            icon_name
            uniqueness
            is_unit_upgrade
            is_hidden_in_ui
            name
            tooltip
        }
        ... on attribute_effect {
            phase
            attribute
        }
    }

}
